matrix:
  include:
    - language: ruby
      rvm:
        - "2.6.3"
        - "2.5.5"
      gemfile: ruby/Gemfile
      before_script:
        - cd ruby
      script: bundle exec rspec spec
    - language: elixir
      elixir:
        - "1.8"
        - "1.7"
      otp_release:
        - "21.0"
      sudo: false
      before_install:
        - cd elixir
      script: mix coveralls.json